import React from "react";
import Link from "next/link";
import type {
  ComparisonRow,
  FaqItem,
  Article,
  WhyUgcContent,
  UgcComparisonContent,
  PricingContent,
  FaqContent,
  ArticlesContent,
  HeroOverrides,
} from "@/types/platform";

export const reportingHeroOverrides: HeroOverrides = {
  label: "Social Media Performance & Analytics",
  headline: "Track Creator Content Performance Across Every Channel",
  stats: [
    { value: "Real-time", label: "Performance tracking" },
    { value: "All Platforms", label: "Unified dashboard" },
    { value: "ROI", label: "Attribution built-in" },
  ],
  primaryCta: { text: "Start Tracking", href: "https://app.sideshift.app/signup", event: "start_tracking_reporting_hero" },
  secondaryCta: { text: "Book a Demo", href: "/contact", event: "book_demo_reporting_hero" },
};

export const reportingWhyUgc: WhyUgcContent = {
  label: "Why Performance Analytics?",
  heading: "Know exactly what's working — and double down.",
  paragraphs: [
    "Running UGC without performance data is flying blind. SideShift tracks every piece of creator content across Instagram, TikTok, YouTube, and Facebook — giving you real-time views, engagement, and conversion metrics in one dashboard.",
    "Identify your top-performing creators and content formats, then reinvest in what drives results instead of guessing.",
  ],
  cards: [
    { title: "Cross-Platform Tracking", description: "Monitor views, likes, shares, comments, and saves across Instagram, TikTok, YouTube, and Facebook — all from a single dashboard." },
    { title: "Creator Scorecards", description: "See which creators consistently deliver results. Rank by engagement rate, content quality, and ROI to build your dream roster." },
    { title: "ROI Attribution", description: "Connect content performance to business outcomes. Track clicks, conversions, and revenue generated by each creator and campaign." },
  ],
};

export const reportingUgcComparison: UgcComparisonContent = {
  label: "UGC vs Traditional",
  heading: "Why data-driven UGC outperforms gut-feel marketing",
  description: "Performance analytics turn creator content from a cost center into a measurable growth channel.",
  ugcColumnHeader: "Data-Driven UGC",
  traditionalColumnHeader: "Traditional Marketing",
};

export const reportingComparisonRows: ComparisonRow[] = [
  { category: "Measurement", ugc: "Real-time metrics across all platforms", traditional: "Monthly reports with lagging indicators" },
  { category: "Optimization", ugc: "Identify top creators and formats instantly", traditional: "Rely on subjective creative judgment" },
  { category: "Attribution", ugc: "Track from impression to conversion", traditional: "Unclear ROI and brand lift studies" },
  { category: "Speed", ugc: "Spot trends in hours, pivot in days", traditional: "Quarterly reviews and slow pivots" },
  { category: "Cost Efficiency", ugc: "Reinvest in proven performers", traditional: "Spread budget evenly regardless of results" },
];

export const reportingPricing: PricingContent = {
  heading: "Analytics included in every plan",
  subheading: "No add-ons. Performance tracking comes standard.",
};

export const reportingFaqContent: FaqContent = {
  heading: "Performance & Analytics FAQ",
  subheading: "Everything you need to know about tracking creator content performance.",
};

export const reportingFaqData: FaqItem[] = [
  { id: 1, question: "Which platforms do you track?", answer: "We track content performance across Instagram (Reels, Stories, Feed), TikTok, YouTube (Shorts and long-form), and Facebook — all in one dashboard." },
  { id: 2, question: "Is performance tracking real-time?", answer: "Yes — metrics update automatically as content goes live and accumulates views, engagement, and interactions." },
  { id: 3, question: "Can I export reports?", answer: "Yes — export performance reports as CSV or PDF for client presentations, internal reviews, or stakeholder updates." },
  { id: 4, question: "Do you track conversions?", answer: "Yes — connect your tracking links or UTM parameters to measure clicks, sign-ups, purchases, and other conversion events driven by creator content." },
  { id: 5, question: "How do creator scorecards work?", answer: "Each creator gets a performance profile based on their content history, engagement rates, audience quality, and past campaign results on SideShift." },
];

export const reportingArticlesContent: ArticlesContent = {
  label: "Related Articles",
  heading: "Learn more about UGC analytics",
};

export const reportingArticles: Article[] = [
  { slug: "instagram-engagement-rate", title: "How to Calculate Instagram Engagement Rate", excerpt: "The metrics that matter and how to track them effectively.", category: "Analytics", readTime: "6 min read" },
  { slug: "what-is-a-good-roas", title: "What is a Good ROAS? 2026 Benchmarks by Industry", excerpt: "Benchmark your ad performance against industry standards.", category: "Paid Media", readTime: "7 min read" },
  { slug: "tiktok-vs-instagram-marketing-results", title: "TikTok vs Instagram: Which Drives Better Marketing Results?", excerpt: "Data-backed comparison of the two biggest creator platforms.", category: "Analytics", readTime: "6 min read" },
];
